"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var express_1 = require("express");
var user_controller_1 = require("../controllers/user.controller");
var authentication_1 = require("../middleware/authentication");
var telegram_controller_1 = require("../controllers/telegram.controller");
var router = (0, express_1.Router)();
router.get("/", function (req, res) {
    res.send({ response: "hello world from user route" });
});
router.get('/get', authentication_1.default, user_controller_1.getProfile);
router.post("/sendotp", user_controller_1.sendOtp);
router.post("/verifyotp", user_controller_1.verifyOtp);
router.post("/login", user_controller_1.login);
router.put("/update", authentication_1.default, user_controller_1.updateProfile);
router.get("/resetPass", authentication_1.default, user_controller_1.resetPasswordLink);
router.post("/reset", user_controller_1.resetPassword);
router.post("/sendquickLogin", user_controller_1.quickLoginLink);
router.get("/quickLogin", user_controller_1.quickLogin);
router.put('/telegram', authentication_1.default, telegram_controller_1.telegramUpadate);
exports.default = router;
